FROM node:12

WORKDIR /opt/app

COPY package.json .
COPY yarn.lock .
COPY packages/server/package.json packages/server/package.json

RUN yarn install --frozen-lockfile

COPY packages/server packages/server
COPY packages/_shared packages/_shared

WORKDIR /opt/app/packages/server

RUN yarn build

CMD [ "node", "dist/index.js" ]
